name: Archive Inactive Repositories

on:
  schedule:
    - cron: '0 0 1 * *' # Runs on the first day of every month
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Archive Inactive Repositories
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        REPOS=$(gh repo list YOUR_ORG --limit 100 --json name --jq '.[] | select(.pushedAt < now - 31536000) | .name') # Repositories not pushed to in the last year
        for REPO in $REPOS; do
          echo "Archiving repository: $REPO"
          gh api -X PATCH "repos/YOUR_ORG/$REPO" -f archived=true
        done
